-- Core tests: spans, questions, decode, policy.
--
-- These deliberately do NOT require('jev.actions'): the catalogs below are
-- inline so the pure-Lua core can be tested on its own. The three-action
-- catalog and the "find three test files in the git changed stuff" utterance
-- are the worked example from the research notes, generated by running the
-- reference questions.js/decode.js — every id, wording and probability below
-- is copied from that run.

local spans = require('jev.spans')
local questions = require('jev.questions')
local decode = require('jev.decode')
local policy = require('jev.policy')

--------------------------------------------------------------------------------
-- Inline catalogs
--------------------------------------------------------------------------------

--- The research notes' worked example, as JevAction entries.
local worked = {
  {
    name = 'goto_definition',
    description = 'Jump to the definition of the symbol under the cursor.',
    readOnly = true,
    params = {},
    run = function() end,
  },
  {
    name = 'find_files',
    description = 'Fuzzy-find files in the project by name.',
    readOnly = true,
    params = {
      query = { type = 'string', required = true, description = 'Text to match against file paths' },
      scope = {
        type = 'enum',
        description = 'Where to search',
        enum = { project = '', open_buffers = '', git_changed = '' },
      },
      limit = { type = 'integer', description = 'How many results', min = 1, max = 10 },
    },
    run = function() end,
  },
  {
    name = 'split_window',
    description = 'Split the current window.',
    params = {
      direction = { type = 'enum', required = true, enum = { horizontal = '', vertical = '' } },
      focus = { type = 'boolean', description = 'move the cursor into the new window' },
    },
    run = function() end,
  },
}

--- Same three plus an unbounded integer, a destructive action and a set.
local wider = vim.list_extend({}, worked)
vim.list_extend(wider, {
  {
    name = 'goto_line',
    description = 'Move the cursor to a line.',
    readOnly = true,
    params = { line = { type = 'integer', required = true, description = 'Line number' } },
    run = function() end,
  },
  {
    name = 'quit_all',
    description = 'Close every window and quit.',
    destructive = true,
    params = {},
    run = function() end,
  },
  {
    name = 'show_diagnostics',
    description = 'List diagnostics in the quickfix window.',
    readOnly = true,
    params = {
      severity = { type = 'array', description = 'Which levels to show', enum = { error = '', warn = '', hint = '' } },
    },
    run = function() end,
  },
})

local UTTERANCE = 'find three test files in the git changed stuff'

--- The 19 spans the reference implementation produces for UTTERANCE, in order.
local WORKED_SPANS = {
  'find', 'three', 'test', 'files', 'git', 'changed', 'stuff',
  'find three', 'three test', 'test files', 'git changed', 'changed stuff',
  'find three test', 'three test files', 'git changed stuff',
  'find three test files', 'files in the git',
  'test files in the git', 'files in the git changed',
}

local function keys_of(tbl)
  local keys = {}
  for k in pairs(tbl or {}) do
    keys[#keys + 1] = k
  end
  table.sort(keys)
  return keys
end

local function noul(value)
  return { type = 'noul', noul = value }
end

local function choice(picked, probabilities, confidence)
  return { type = 'choice', choice = picked, probabilities = probabilities, confidence = confidence }
end

--------------------------------------------------------------------------------
-- spans.lua
--------------------------------------------------------------------------------

describe('spans.spans', function()
  it("lifts the user's own words, never starting or ending on a function word", function()
    -- Straight from the reference test suite (test/core.test.js).
    local found = spans.spans('find me some oat milk under $5?')
    ok(vim.tbl_contains(found, 'oat milk'), 'expected "oat milk"')
    ok(vim.tbl_contains(found, '$5'), 'expected "$5"')
    ok(not vim.tbl_contains(found, 'me'), '"me" is an edge stopword')
    ok(not vim.tbl_contains(found, 'some oat milk'), '"some" is an edge stopword')
    for _, s in ipairs(found) do
      ok(not s:find('%?$'), 'no span may keep trailing punctuation: ' .. s)
    end
  end)

  it('returns shortest first and keeps interior stopwords', function()
    eq(spans.spans(UTTERANCE), WORKED_SPANS)
  end)

  it('dedupes case-insensitively but keeps the original casing', function()
    eq(spans.spans('Test test'), { 'Test', 'Test test' })
  end)

  it('has nothing to say about an empty utterance', function()
    eq(spans.spans(''), {})
    eq(spans.spans('the a of to'), {}, 'all edge stopwords')
  end)

  it('caps the candidate list', function()
    local many = {}
    for i = 1, 200 do
      many[i] = 'word' .. i
    end
    eq(#spans.spans(table.concat(many, ' ')), 120, 'capped at 120, under the API 255-option limit')
  end)
end)

describe('spans.numbers', function()
  it('parses digits, words, compounds and phrases in code', function()
    eq(spans.numbers('two cartons and 3.5 lbs, under twenty five bucks'), {
      { value = 2, text = 'two' },
      { value = 3.5, text = '3.5' },
      { value = 25, text = 'twenty five' },
    })
    eq(spans.numbers('half a dozen eggs'), { { value = 6, text = 'half a dozen' } })
    eq(spans.numbers('a couple of limes and a dozen eggs'), {
      { value = 2, text = 'a couple of' },
      { value = 12, text = 'a dozen' },
    })
    eq(spans.numbers('no numbers here'), {})
  end)

  it('handles hyphenated tens and rejects overlaps', function()
    eq(spans.numbers('line twenty-one'), { { value = 21, text = 'twenty-one' } })
    -- "half a dozen" claims its span, so the trailing "a dozen" cannot also match.
    eq(#spans.numbers('half a dozen'), 1)
  end)

  it('dedupes by value, keeping the first mention', function()
    eq(spans.numbers('three files and three more'), { { value = 3, text = 'three' } })
  end)

  it('finds the number in the worked example', function()
    eq(spans.numbers(UTTERANCE), { { value = 3, text = 'three' } })
  end)
end)

--------------------------------------------------------------------------------
-- questions.lua
--------------------------------------------------------------------------------

describe('questions.build (worked example)', function()
  local built = questions.build(worked, UTTERANCE)
  local q = built.questions

  it('asks exactly the eight questions the reference produces', function()
    eq(keys_of(q), {
      '__tool__',
      'find_files::limit',
      'find_files::limit?',
      'find_files::query',
      'find_files::scope',
      'find_files::scope?',
      'split_window::direction',
      'split_window::focus',
    })
  end)

  it('routes over action names plus __none__', function()
    eq(q['__tool__'].type, 'choice')
    eq(q['__tool__'].instructions, "Which action does the user's request call for?")
    eq(keys_of(q['__tool__'].criteria), { '__none__', 'find_files', 'goto_definition', 'split_window' })
    eq(q['__tool__'].criteria.find_files, 'Fuzzy-find files in the project by name.')
    eq(
      q['__tool__'].criteria['__none__'],
      'None of these: the request is conversation, unclear, unfinished, or needs something these actions do not do.'
    )
  end)

  it("offers a free-text param the user's own words plus (not stated)", function()
    local criteria = q['find_files::query'].criteria
    eq(q['find_files::query'].type, 'choice')
    eq(
      q['find_files::query'].instructions,
      'For the "find_files" action: which exact words of the user\'s request give "query" (Text to match against file paths)?'
    )
    for _, span in ipairs(WORKED_SPANS) do
      eq(criteria[span], vim.NIL, 'span ' .. span .. ' should be a null-described option')
    end
    eq(criteria['(not stated)'], 'The request does not say this.')
    eq(#keys_of(criteria), #WORKED_SPANS + 1)
  end)

  it('turns an enum into a Choice and a small integer range into a Choice over the range', function()
    eq(q['find_files::scope'].type, 'choice')
    eq(
      q['find_files::scope'].instructions,
      'For the "find_files" action: which option does the user\'s request indicate for "scope" (Where to search)?'
    )
    eq(keys_of(q['find_files::scope'].criteria), { 'git_changed', 'open_buffers', 'project' })
    eq(keys_of(q['find_files::limit'].criteria), { '1', '10', '2', '3', '4', '5', '6', '7', '8', '9' })
    eq(q['find_files::limit'].criteria['10'], vim.NIL)
  end)

  it('turns a boolean into a Noul and never asks whether it was stated', function()
    eq(q['split_window::focus'].type, 'noul')
    eq(
      q['split_window::focus'].instructions,
      'For the "split_window" action: does the user\'s request call for "focus" (move the cursor into the new window)?'
    )
    eq(q['split_window::focus?'], nil, 'flags never get a stated? Noul')
  end)

  it('asks "is it stated?" for optional params only', function()
    eq(q['find_files::scope?'].type, 'noul')
    eq(
      q['find_files::scope?'].instructions,
      'For the "find_files" action: does the user\'s request state or clearly imply "scope" (Where to search)?'
    )
    eq(q['find_files::limit?'].type, 'noul')
    eq(q['find_files::query?'], nil, 'required params are always filled')
    eq(q['split_window::direction?'], nil, 'required params are always filled')
  end)

  it('omits the description parentheses when there is none', function()
    eq(
      q['split_window::direction'].instructions,
      'For the "split_window" action: which option does the user\'s request indicate for "direction"?'
    )
  end)

  it('hands decode a plan it does not have to re-parse', function()
    eq(built.meta.state, UTTERANCE, 'state for the request is the utterance string')
    eq(built.meta.spans, WORKED_SPANS)
    eq(built.meta.numbers, { { value = 3, text = 'three' } })
    local kinds = {}
    for _, param in ipairs(built.meta.plan.find_files.params) do
      kinds[param.label] = param.kind
    end
    eq(kinds, { query = 'span', scope = 'choice', limit = 'choice' })
  end)
end)

describe('questions.build (other shapes)', function()
  it('offers the numbers the user stated for an unbounded integer', function()
    local q = questions.build(wider, 'go to line 40').questions
    eq(q['goto_line::line'].type, 'choice')
    eq(q['goto_line::line'].instructions, 'For the "goto_line" action: which number in the user\'s request is "line" (Line number)?')
    eq(q['goto_line::line'].criteria['40'], 'The user wrote "40".')
    eq(q['goto_line::line'].criteria['(not stated)'], 'None of these numbers is this.')
    eq(q['goto_line::line?'], nil, 'required')
  end)

  it('omits a span or number question with no candidates (the source omits, it does not stub)', function()
    local q = questions.build(wider, '').questions
    eq(q['find_files::query'], nil, 'no words said, nothing to choose from')
    eq(q['goto_line::line'], nil, 'no numbers said, nothing to choose from')
    eq(q['find_files::query?'], nil)
    ok(q['find_files::scope'] ~= nil, 'an enum still has its own options')
    ok(q['__tool__'] ~= nil)
  end)

  it('asks one Noul per member of a set, and never a stated? Noul', function()
    local q = questions.build(wider, 'show me errors and warnings').questions
    eq(q['show_diagnostics::severity'], nil, 'a set has no value question of its own')
    eq(q['show_diagnostics::severity::error'].type, 'noul')
    eq(
      q['show_diagnostics::severity::error'].instructions,
      'For the "show_diagnostics" action: does the user\'s request ask for "error"? It is one option of "severity" (Which levels to show).'
    )
    ok(q['show_diagnostics::severity::warn'] ~= nil)
    ok(q['show_diagnostics::severity::hint'] ~= nil)
    eq(q['show_diagnostics::severity?'], nil)
  end)

  it('draws the small-range line where the source does (max - min <= 24)', function()
    local function kind_of(param)
      local q = questions.build({ { name = 'a', description = 'd', params = { n = param } } }, 'pick 7').questions
      return q['a::n'] and #keys_of(q['a::n'].criteria) or nil
    end
    eq(kind_of({ type = 'integer', min = 1, max = 25 }), 25, 'max - min == 24 is still a Choice over the range')
    eq(kind_of({ type = 'integer', min = 1, max = 26 }), 2, 'wider than that falls back to the numbers said, plus (not stated)')
    eq(kind_of({ type = 'integer' }), 2, 'no bounds at all is a number question')
    eq(kind_of({ type = 'number', min = 1, max = 3 }), 2, 'only integers get a range Choice')
  end)

  it('asks nothing for a param type it cannot fill', function()
    local built = questions.build({ { name = 'a', description = 'd', params = { blob = { type = 'table' } } } }, 'hi')
    eq(built.questions['a::blob'], nil)
    eq(built.meta.plan.a.params[1].kind, 'unfillable')
    eq(built.meta.plan.a.params[1].qid, nil)
  end)

  it('clips a long description to 600 characters', function()
    local long = string.rep('x', 700)
    local q = questions.build({ { name = 'big', description = long, params = {} } }, 'hi').questions
    local text = q['__tool__'].criteria.big
    eq(vim.fn.strchars(text), 600)
    ok(text:sub(-3) == '…', 'clipped descriptions end in an ellipsis')
  end)

  it('honours opts.only', function()
    local q = questions.build(worked, UTTERANCE, { only = { 'split_window' } }).questions
    eq(keys_of(q), { '__tool__', 'split_window::direction', 'split_window::focus' })
    eq(keys_of(q['__tool__'].criteria), { '__none__', 'split_window' })
  end)
end)

--------------------------------------------------------------------------------
-- decode.lua
--------------------------------------------------------------------------------

--- The verbatim answers from the research notes' end-to-end run.
local function worked_answers(overrides)
  local answers = {
    ['__tool__'] = choice('find_files', {
      find_files = 0.97,
      goto_definition = 0.02,
      split_window = 0.01,
      ['__none__'] = 0.0,
    }, 0.93),
    ['find_files::query'] = choice('test files', {
      ['test files'] = 0.71,
      ['three test files'] = 0.2,
      ['(not stated)'] = 0.02,
    }, 0.6),
    ['find_files::scope'] = choice('git_changed', { git_changed = 0.95, project = 0.04, open_buffers = 0.01 }, 0.9),
    ['find_files::scope?'] = noul(0.93),
    ['find_files::limit'] = choice('3', { ['3'] = 0.96, ['1'] = 0.01 }, 0.94),
    ['find_files::limit?'] = noul(0.88),
    ['split_window::direction'] = choice('vertical', { vertical = 0.5, horizontal = 0.5 }, 0.0),
    ['split_window::focus'] = noul(0.1),
  }
  for key, value in pairs(overrides or {}) do
    answers[key] = value ~= vim.NIL and value or nil
  end
  return answers
end

describe('decode.decode', function()
  local built = questions.build(worked, UTTERANCE)

  it('turns the worked example into a runnable call', function()
    local call = decode.decode(worked, worked_answers(), built.meta)
    eq(call.name, 'find_files')
    eq(call.args, { query = 'test files', scope = 'git_changed', limit = 3 })
    eq(call.missing, {})
    near(call.routeProbability, 0.97)
    near(call.confidence, 0.71, 1e-9, 'confidence is the weakest judgement, not a product')
    eq(call.action.name, 'find_files')
    eq(decode.format_call(call), 'find_files {limit=3, query=test files, scope=git_changed}')
  end)

  it('takes the per-argument probability from probabilities[choice], never confidence', function()
    local call = decode.decode(worked, worked_answers(), built.meta)
    near(call.details.query.probability, 0.71, 1e-9, 'not the answer confidence 0.6')
    near(call.details.scope.probability, 0.93, 1e-9, 'min(stated 0.93, picked 0.95)')
    near(call.details.limit.probability, 0.88, 1e-9, 'min(stated 0.88, picked 0.96)')
    eq(call.details.scope.stated, true)
  end)

  it('coerces a choice key back to the value the catalog declared', function()
    local call = decode.decode(worked, worked_answers(), built.meta)
    eq(type(call.args.limit), 'number', '"3" came back as the number 3')
  end)

  it('reads an unbounded integer back as a number', function()
    local b = questions.build(wider, 'go to line 40')
    local call = decode.decode(wider, {
      ['__tool__'] = choice('goto_line', { goto_line = 0.99 }),
      ['goto_line::line'] = choice('40', { ['40'] = 0.99 }),
    }, b.meta)
    eq(call.args, { line = 40 })
    eq(type(call.args.line), 'number')
  end)

  it('omits an optional param the request did not state', function()
    local call = decode.decode(worked, worked_answers({ ['find_files::scope?'] = noul(0.05) }), built.meta)
    eq(call.args.scope, nil)
    eq(call.details.scope.omitted, true)
    near(call.details.scope.probability, 0.95, 1e-9, 'a correctly omitted optional is 1 - stated')
  end)

  it('reports a required param nobody stated as missing, and never guesses it', function()
    local call = decode.decode(
      worked,
      worked_answers({ ['find_files::query'] = choice('(not stated)', { ['(not stated)'] = 0.8 }) }),
      built.meta
    )
    eq(call.missing, { 'query' })
    eq(call.args.query, nil)
    eq(policy.decide(call), 'incomplete')
  end)

  it('reports a required param with no question at all as missing', function()
    local empty = questions.build(worked, '')
    local call = decode.decode(worked, { ['__tool__'] = choice('find_files', { find_files = 0.9 }) }, empty.meta)
    eq(call.missing, { 'query' })
    eq(call.details.query.probability, 1, 'no question asked is not a doubt')
    near(call.confidence, 0.9)
    eq(policy.decide(call), 'incomplete')
  end)

  it('decodes a flag from its Noul, both ways', function()
    local answers = worked_answers({
      ['__tool__'] = choice('split_window', { split_window = 0.9, find_files = 0.1 }),
      ['split_window::direction'] = choice('vertical', { vertical = 0.99, horizontal = 0.01 }),
    })
    local off = decode.decode(worked, answers, built.meta)
    eq(off.args, { direction = 'vertical' }, 'a false flag is left out so the default stands')
    near(off.details.focus.probability, 0.9, 1e-9, 'max(noul, 1 - noul)')

    answers['split_window::focus'] = noul(0.95)
    local on = decode.decode(worked, answers, built.meta)
    eq(on.args, { direction = 'vertical', focus = true })
    near(on.details.focus.probability, 0.95, 1e-9)
  end)

  it('decodes a set from one Noul per member', function()
    local b = questions.build(wider, 'show me errors and warnings')
    local call = decode.decode(wider, {
      ['__tool__'] = choice('show_diagnostics', { show_diagnostics = 0.95 }),
      ['show_diagnostics::severity::error'] = noul(0.9),
      ['show_diagnostics::severity::warn'] = noul(0.8),
      ['show_diagnostics::severity::hint'] = noul(0.1),
    }, b.meta)
    eq(call.args, { severity = { 'error', 'warn' } })
    near(call.details.severity.probability, 0.8, 1e-9, 'the least certain member')
  end)

  it('returns no action for __none__ or an unknown route', function()
    local none = decode.decode(worked, worked_answers({
      ['__tool__'] = choice('__none__', { ['__none__'] = 0.93, find_files = 0.07 }),
    }), built.meta)
    eq(none.name, nil)
    eq(none.action, nil)
    eq(none.args, {})
    eq(none.missing, {})
    near(none.routeProbability, 0.93)
    eq(policy.decide(none), 'none')

    local gone = decode.decode(worked, worked_answers({
      ['__tool__'] = choice('vanished_action', { vanished_action = 0.99 }),
    }), built.meta)
    eq(gone.name, nil, 'a route naming an action that is not in the catalog')
  end)

  it('reports the runners-up so the panel can name the best guess', function()
    local call = decode.decode(worked, worked_answers(), built.meta)
    eq(call.routes[1].name, 'find_files')
    near(call.routes[1].probability, 0.97)
    eq(#call.routes, 3, 'top three')
    local none_route = decode.decode(worked, worked_answers({
      ['__tool__'] = choice('__none__', { ['__none__'] = 0.8, goto_definition = 0.15, find_files = 0.05 }),
    }), built.meta)
    eq(none_route.routes[1].name, nil, '__none__ reports as no action at all')
    eq(none_route.routes[1].key, '__none__')
  end)

  it('survives JSON nulls and junk answers', function()
    local call = decode.decode(worked, {
      ['__tool__'] = { type = 'choice', choice = 'find_files', probabilities = { find_files = 0.9, ['__none__'] = vim.NIL } },
      ['find_files::query'] = choice('test files', { ['test files'] = 0.9 }),
      ['find_files::scope'] = { type = 'choice', choice = vim.NIL, probabilities = vim.NIL },
      ['find_files::scope?'] = { type = 'noul', noul = vim.NIL },
      ['find_files::limit'] = vim.NIL,
      ['find_files::limit?'] = { type = 'noul' },
    }, built.meta)
    eq(call.name, 'find_files')
    eq(call.args, { query = 'test files' })
    eq(call.details.scope.omitted, true, 'a null noul reads as 0, so the param was not stated')
    eq(call.details.limit.omitted, true)
    near(call.confidence, 0.9)
  end)

  it('accepts a boolean Noul with or without a probability, defensively', function()
    -- The documented shape is { type = "noul", noul = <0..1> } and Noul answers
    -- carry no confidence. These are the defensive fallbacks.
    local function focus(answer)
      local answers = worked_answers({
        ['__tool__'] = choice('split_window', { split_window = 0.9 }),
        ['split_window::direction'] = choice('vertical', { vertical = 0.99 }),
        ['split_window::focus'] = answer,
      })
      return decode.decode(worked, answers, built.meta).details.focus
    end
    eq(focus({ type = 'noul', noul = true }).value, true)
    near(focus({ type = 'noul', noul = true }).probability, 1)
    eq(focus({ type = 'noul', noul = false }).omitted, true)
    eq(focus({ type = 'noul', noul = true, probability = 0.82 }).value, true)
    near(focus({ type = 'noul', noul = true, probability = 0.82 }).probability, 0.82)
    near(focus({ type = 'noul', noul = false, probability = 0.9 }).probability, 0.9, 1e-9, 'false at p=0.9 is a noul of 0.1')
    near(focus({ type = 'noul', probability = 0.7 }).probability, 0.7, 1e-9, 'probability alone')
    eq(focus({ type = 'noul' }).omitted, true, 'nothing usable reads as 0')
  end)

  it("lets a user's pick overrule the route without asking again", function()
    local call = decode.decode(worked, worked_answers({
      ['__tool__'] = choice('find_files', { find_files = 0.3, split_window = 0.25 }),
    }), built.meta, { pick = 'split_window' })
    eq(call.name, 'split_window')
    eq(call.args, { direction = 'vertical' })
    eq(call.picked, true)
    near(call.routeProbability, 0.25, 1e-9, "Jev's own odds are still reported")
    near(call.confidence, 0.5, 1e-9, 'only the arguments are left in doubt')
    eq(decode.decode(worked, worked_answers(), built.meta, { pick = 'gone' }).name, 'find_files', 'a stale pick falls back')
  end)
end)

--------------------------------------------------------------------------------
-- policy.lua
--------------------------------------------------------------------------------

describe('policy.decide', function()
  local built = questions.build(worked, UTTERANCE)
  local wider_built = questions.build(wider, UTTERANCE)

  local function call_for(overrides, catalog, meta)
    return decode.decode(catalog or worked, worked_answers(overrides), meta or built.meta)
  end

  it('auto: read-only and confident', function()
    local call = call_for({
      ['find_files::query'] = choice('test files', { ['test files'] = 0.9 }),
    })
    near(call.confidence, 0.88, 1e-9)
    eq(policy.decide(call), 'auto')
    eq(policy.decide(call, { live = false }), 'ready', 'no live mode means no auto')
  end)

  it('ready: read-only but under the auto threshold', function()
    local call = call_for()
    near(call.confidence, 0.71, 1e-9)
    eq(policy.decide(call), 'ready')
  end)

  it('ready: a state-changing action never auto-runs, however confident', function()
    local call = call_for({
      ['__tool__'] = choice('split_window', { split_window = 0.99 }),
      ['split_window::direction'] = choice('vertical', { vertical = 0.99, horizontal = 0.01 }),
      ['split_window::focus'] = noul(0.01),
    })
    near(call.confidence, 0.99, 1e-9)
    eq(policy.decide(call), 'ready')
  end)

  it('confirm: a destructive action always asks, however confident', function()
    local call = decode.decode(wider, {
      ['__tool__'] = choice('quit_all', { quit_all = 0.99 }),
    }, wider_built.meta)
    near(call.confidence, 0.99)
    eq(policy.decide(call), 'confirm')
  end)

  it('confirm: below the confirm threshold', function()
    local call = call_for({
      ['__tool__'] = choice('split_window', { split_window = 0.9 }),
    })
    near(call.confidence, 0.5, 1e-9, 'a 50/50 direction')
    eq(policy.decide(call), 'confirm')
  end)

  it('confirm: a flagged catalog never auto-runs', function()
    local call = call_for({ ['find_files::query'] = choice('test files', { ['test files'] = 0.9 }) })
    eq(policy.decide(call, { flagged = true }), 'confirm')
  end)

  it('incomplete: a required argument has no value yet', function()
    local call = call_for({ ['find_files::query'] = choice('(not stated)', { ['(not stated)'] = 0.9 }) })
    eq(policy.decide(call), 'incomplete')
  end)

  it('none: no action, or a route under the route threshold', function()
    eq(policy.decide(nil), 'none')
    eq(policy.decide(call_for({ ['__tool__'] = choice('__none__', { ['__none__'] = 0.99 }) })), 'none')
    eq(policy.decide(call_for({ ['__tool__'] = choice('find_files', { find_files = 0.3 }) })), 'none', 'route < 0.5')
  end)

  it('order of evaluation: missing beats destructive beats read-only', function()
    local incomplete = decode.decode(wider, {
      ['__tool__'] = choice('goto_line', { goto_line = 0.99 }),
    }, questions.build(wider, 'move down').meta)
    eq(incomplete.missing, { 'line' })
    eq(policy.decide(incomplete), 'incomplete', 'a missing argument outranks the read-only auto path')
  end)

  it('uses the documented default thresholds and lets them be overridden', function()
    eq(policy.DEFAULTS, { route = 0.5, auto = 0.8, confirm = 0.6 })
    local call = call_for()
    eq(policy.decide(call, { thresholds = { auto = 0.7 } }), 'auto', 'confidence 0.71 clears a 0.7 auto bar')
    eq(policy.decide(call, { thresholds = { confirm = 0.75 } }), 'confirm')
    eq(policy.decide(call, { thresholds = { route = 0.99 } }), 'none', 'route 0.97 under a 0.99 bar')
  end)
end)

--------------------------------------------------------------------------------
-- Serialization
--------------------------------------------------------------------------------

describe('questions JSON', function()
  it('round-trips, with every Choice criteria as a JSON object', function()
    local built = questions.build(worked, UTTERANCE)
    local encoded = vim.json.encode(built.questions)

    ok(not encoded:find('"criteria":[', 1, true), 'no criteria may encode as a JSON array')

    local back = vim.json.decode(encoded)
    eq(keys_of(back), {
      '__tool__',
      'find_files::limit',
      'find_files::limit?',
      'find_files::query',
      'find_files::scope',
      'find_files::scope?',
      'split_window::direction',
      'split_window::focus',
    })
    eq(back['__tool__'].type, 'choice')
    eq(back['__tool__'].criteria.find_files, 'Fuzzy-find files in the project by name.')
    eq(back['find_files::query'].criteria['test files'], vim.NIL, 'a null-described option stays null')
    eq(back['find_files::query'].criteria['(not stated)'], 'The request does not say this.')
    eq(keys_of(back['find_files::scope'].criteria), { 'git_changed', 'open_buffers', 'project' })
    eq(back['find_files::scope?'].type, 'noul')
    eq(back['find_files::scope?'].criteria, nil, 'a bare Noul carries no criteria')

    for id, question in pairs(back) do
      if question.type == 'choice' then
        ok(type(question.criteria) == 'table', id .. ' criteria must decode as a table')
        ok(#question.criteria == 0, id .. ' criteria must be an object, not an array')
        ok(next(question.criteria) ~= nil, id .. ' criteria must not be empty')
      end
    end
  end)

  it('encodes empty criteria as {} and not []', function()
    local built = questions.build({
      { name = 'odd', description = 'An action with an empty option set.', params = { pick = { type = 'enum', required = true, enum = {} } } },
    }, 'hi')
    local encoded = vim.json.encode(built.questions)
    ok(encoded:find('"criteria":{}', 1, true), 'expected an empty JSON object: ' .. encoded)
  end)

  it('encodes the whole request body the client will POST', function()
    local built = questions.build(worked, UTTERANCE)
    local body = vim.json.encode({ state = built.meta.state, model = 'jev-latest', questions = built.questions })
    local back = vim.json.decode(body)
    eq(back.state, UTTERANCE)
    eq(back.model, 'jev-latest')
    eq(back.questions['__tool__'].instructions, "Which action does the user's request call for?")
  end)
end)
